const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const SHOW_PROGRESS = 'SHOW_PROGRESS';
const HIDE_PROGRESS = 'HIDE_PROGRESS';
const INCREMENT_MONTH = 'INCREMENT_MONTH';
const DECREMENT_MONTH = 'DECREMENT_MONTH';

export default {
	LOGIN,
	LOGOUT,
	SHOW_PROGRESS,
	HIDE_PROGRESS,
	INCREMENT_MONTH,
	DECREMENT_MONTH
}